### ISSUE TITLE
User::SetPacketData, User::GetPacket  멀티 쓰레드 이슈

### ISSUE THREAD

**Issue by ghost** [jacking75/edu_cpp_IOCP#1]
WorkThread에서는 User::SetPacketData 호출되고
ProcessPacketThread에서는 User::GetPacket  호출되는데
서로 다른 쓰레드에서 lock없이 SetPacketData, GetPacket  함수 안 쪽에서   User의 멤버 변수(공유자원)을 참조하고 변경까지 하고 있는데 이 부분 문제가 안되는건가요?

WorkThread에서 그냥 User::SetPacketData와 User::GetPacket  하는 부분을 같이 진행하고
완성된 패킷만 별도의 큐에 담고 ProcessPacketThread에서는 완성된 패킷만 큐에서 빼오는 방식으로하면 어떨까요? (큐에다 lock걸어야해서 성능 이슈? 생길 수도)

저렇게 분리하신 이유가 있으시면 그게 궁금하고 제가 제시한 방안은 어떻게 생각하시는지 궁금합니다.

그리고 11단계, 12단계는 진행 하실 생각이 있으신지..? 아니면 그냥 공부하는 사람한테 수행과제로 내신건가요..?

항상 감사합니다~!

**Comment by jacking75** [comment]
이야기 하신대로 문제가 있습니다. 
SetPacketData, GetPacket 함수 안의 공유 변수가 스레드 세이프하지 않습니다.

이 프로젝트는 실습을 위해서 만든 것입니다. 그래서 버그가 있는지 꼼꼼하게 확인하지 않았고, 혹 알아도 고칠 예정은 없습니다. 주석을 달아 놓을 수는 있지만. 이유는 학습하면서 고치기 바라기 때문입니다.

또 10단계까지 빠르게 만들어가는 것을 목적으로 하고 있어서 최적화가 되어 있지 않습니다. 
이 부분은 11단계에서부터 하는 것을 계획으로 했기 때문입니다.

제가 근무하는 곳에서 이것을 실습으로 사용할 때가 있는데 이때 지정된 기간까지 11단계 이후를 진행하고 있습니다. 실습자가 코드를 만들면 제가 피드백 주면서 리팩토링이나 최적화 작업을 합니다.


지금 구조 보다는
"WorkThread에서 그냥 User::SetPacketData와 User::GetPacket 하는 부분을 같이 진행하고
완성된 패킷만 별도의 큐에 담고 ProcessPacketThread에서는 완성된 패킷만 큐에서 빼오는 방식으로하면 어떨까요?"
이렇게 하는 것이 더 좋습니다. 불필요한 락을 안 만들어도 되니까요
