### ISSUE TITLE
AccepterThread 용도에 대해서 궁금한 점이 있어서 질문 남겨요.

### ISSUE THREAD

**Issue by ghost** [jacking75/edu_cpp_IOCP#2]
//사용자의 접속을 받는 쓰레드
	void AccepterThread()
	{
		while (mIsAccepterRun)
		{
			auto curTimeSec = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now().time_since_epoch()).count();

			for (auto client : mClientInfos)
			{
				if (client->IsConnectd())
				{
					continue;
				}

				if ((UINT64)curTimeSec < client->GetLatestClosedTimeSec())
				{
					continue;
				}

				auto diff = curTimeSec - client->GetLatestClosedTimeSec();
				if (diff <= RE_USE_SESSION_WAIT_TIMESEC)
				{
					continue;
				}

				client->PostAccept(mListenSocket, curTimeSec);
			}
			
			std::this_thread::sleep_for(std::chrono::milliseconds(32));
		}
	}

일단 AccepterThread 쓰레드 소스 코드 내용이에요.

질문 1. 왜 clientInfo_->Close함수가 호출 될 때  소켓을 정리 해주고 바로 clientInfo_->PostAccept() 호출 하면 될 것같은데
왜 별도로 AccepterThread 쓰레드를 둬서 관리를 하는지 궁금합니다.

질문 2. RE_USE_SESSION_WAIT_TIMESEC 이 부분은 왜 3초이고 왜 체크 하는지 궁금합니다. 소켓을 종료하고 난 후에 여유 시간을 둬야 하나요? 그럼 왜 둬야 하는지 궁금해요

질문 3. std::this_thread::sleep_for(std::chrono::milliseconds(32)); 에서 밀리세컨드값이 왜 32인지 궁금합니다. 큰의미는 없을 것 같긴한데 혹시 32밀리세컨드가 최적의 시간이라서 그런건지? 잘 몰라서 여쭤봐요

예전에 흥배님 c#서버 오프라인 하루 강의 하셨을 때 뵀었는데 항상 많은 도움을 받네요 감사합니다.

**Comment by jacking75** [comment]
1. 이것은 이 코드에는 비동기 I/O 요청이 다 끝난 것을 기다리지 않습니다(recv와 send 요청을 한 상태에서 recv에서 끊어짐을 통보 받았는데 아직 send 요청이 취소가 되지 않은 상태이죠). 그래서 모든 I/O 요청이 다 끝난 이후에 PostAccept를 하려고 합니다.

2. 아래 코드는 불필요한 코드입니다.
```
if ((UINT64)curTimeSec < client->GetLatestClosedTimeSec())
{
	continue;
}
```  
시간을 두는 이유는 위의 1번의 이유와 네트워크와 패킷 처리(애플리케이션 측) 스레드가 달라서 패킷처리 스레드에서 끊어진 소켓을 사용하는데 이때 아주 짧은 시간에 이 소켓 객체를 재사용되는 것을 방지하기 위해서 대기 시간을 두고 있습니다.

3. 큰 의미는 없습니다 ^^;

  
제가 도움이 되었다니 저도 많이 기쁩니다^^

**Comment by ghost** [comment]
감사합니다~!
